Quiz Application
elmq0022/hanyu pull request #11
Opened 2017-05-23 12:18 UTC by elmq0022

All the relevant stuff is way on the bottom.   This isn't ready for master yet.

2017-05-23 16:16 UTC, jordanbettis requested changes
This is starting to take shape. You probably want to add "WIP:" to the PR title, to indicate that it shouldn't be merged yet.

2017-05-23 16:16 UTC, jordanbettis commented on quiz/json_response_mixin.py
> +class JSONResponseMixin(object):
Might want to consider putting this in the hanyu app given that you're going to be using it in other packages.

2017-05-23 16:16 UTC, jordanbettis commented on quiz/models.py
> +class Answer(models.Model):
I'm not entirely sure why both `Answer` and `Quiz` have a field to determine if the answer was correct or not. It seems like that should live in either one or the other.

2017-05-23 16:16 UTC, jordanbettis commented on quiz/templates/quiz/quiz.html
> +    {{ block.super }}
See I like to do this:
```python
{% block javascript %}
    ...
    {% block extra_javascript %}{% endblock %}
{% endblock %}
```

In the parent template. That way you don't have to override and then call super in the page template, you can just go ahead and override the empty `{% block extra_javascript %}`.

2017-05-23 16:16 UTC, jordanbettis commented on quiz/templates/quiz/quiz.html
> +            $.ajaxSetup({
You probably want to do the ajaxsetup in the base template so it's available all over your site.

2017-05-23 16:16 UTC, jordanbettis commented on quiz/templates/quiz/quiz.html
> +            alert(selectedAnswerID);
I like to use `console.log()` or `console.debug()` for debugging. This puts it into the javascript console.

2017-05-23 16:16 UTC, jordanbettis commented on quiz/templates/quiz/quiz.html
> +            var end = '<\/label><\/div>'
Why not do something like this:
```javascript
var checkboxHtml = function(answer) {
    return ('<div class="checkbox"><label><input type="radio" name="answer" value=' + answer.pk + '>' 
                + answer.definition + '<\/label><\/div>');
};
```

Then on line 106 you can just do:

```javascript
answerList.push(checkboxHtml(data.answers[i]));
```

2017-05-23 16:16 UTC, jordanbettis commented on quiz/views.py
> +    def get_random_quiz(self):
Is this named correctly?

2017-05-23 23:08 UTC, elmq0022 commented on quiz/models.py
> +class Answer(models.Model):
yes that's redundant.

2017-05-23 23:10 UTC, elmq0022 commented on quiz/templates/quiz/quiz.html
> +            alert(selectedAnswerID);
Good to know. Thanks.

2017-05-24 04:03 UTC, elmq0022 commented on quiz/json_response_mixin.py
> +class JSONResponseMixin(object):
I'm going to put this one on hold.  As I'm ditching the class based view until I get something working.  I'll swing back if there's still time.

2017-05-24 04:05 UTC, elmq0022 commented on quiz/templates/quiz/quiz.html
> +            $.ajaxSetup({
I moved this long with all the other ajax-y functions.  As you said, there's no reason why they are specific to the quiz template.

2017-05-24 04:06 UTC, elmq0022 commented on quiz/templates/quiz/quiz.html
> +            var end = '<\/label><\/div>'
Done.

2017-05-24 04:06 UTC, elmq0022 commented on quiz/views.py
> +    def get_random_quiz(self):
Scratch work left in the code.  I'll clean this up as I go.

2017-05-26 19:08 UTC, elmq0022 commented
Jordan, this is still a little rough around the edges, but good enough to merge into *dev* and probably *main* in my opinion.  Please take a look when you can.

2017-05-28 22:06 UTC, elmq0022 commented
Made final adjustments.  I'm gong to merge this with dev and have it approved pulled from there.  I'm going to start cleaning up a few other things today.

2017-05-28 22:06 UTC, merged